apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: egenintres-se-tls
spec:
  resyncInterval: 10m
  hostAPI: https://eu.infisical.com/api
  updatePolicy: Replace
  deletionPolicy: Delete

  destination:
    projectSlug: homelab
    environmentSlug: prod
    secretsPath: "/certificates"

  push:
    secret:
      secretName: egenintres-se-tls
      secretNamespace: network
      template:
        data:
          EGENINTRES_SE_TLS_KEY: '{{ index .data "tls.crt" | b64enc }}'
          EGENINTRES_SE_TLS_CRT: '{{ index .data "tls.key" | b64enc }}'

  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system