apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: egenintres-se-tls
spec:
  resyncInterval: 10m
  hostAPI: https://eu.infisical.com/api
  updatePolicy: Replace
  deletionPolicy: Delete

  destination:
    projectSlug: homelab
    environmentSlug: prod
    secretsPath: "/certificates"

  push:
    secret:
      secretName: egenintres-se-tls
      secretNamespace: network
  
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system