---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 10m

  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab
        envSlug: prod
        secretsPath: "/certificates"
         # OPTIONAL: If you want to fetch a single Infisical secret, you can specify the secret name here. If not specified, all secrets in the specified scope will be fetched.
        #secretName: CLOUDFLARE_API_TOKEN # ?
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system

  managedKubeSecretReferences:
    - secretName: egenintres-se-tls-test
      secretNamespace: network
      template:
        data:
          tls.key: "{{ .EGENINTRES_SE_TLS_KEY.Value }}"
          tls.crt: "{{ .EGENINTRES_SE_TLS_CRT.Value }}"
