apiVersion: ENC[AES256_GCM,data:/E0=,iv:rb+4CmtJP4i3VJsH153zBu/W6glaSZ+qa5U4qv7eXRo=,tag:vm0aKeTZWIazRv+XbI8acw==,type:str]
kind: ENC[AES256_GCM,data:iq4Zx9Y6,iv:yzrIpg5273GtdI2zj4cTh/dl/VNhGpX+bCcxssZnL0I=,tag:PeMZVWB2WPoN9M/fHhaV0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JDNDyG/0BRllYGbJ2d2PYo/l2A==,iv:XmAfHsHyl3yb0/VnD8uRgGyewcTlVQejGy+riCrHSis=,tag:gPcaXvmGhZKCVD81QLO48Q==,type:str]
    namespace: ENC[AES256_GCM,data:i4QB+7eZZrUE,iv:IyKlDYcqoo3WjzQ1r0uQWFHWeu9A/HFN+uVOXPokymY=,tag:Svc0UrH78DL1VNy3tS1RiA==,type:str]
type: ENC[AES256_GCM,data:CXjPPLa1,iv:wV0cWHofBQ05o78RwKItAY2VJecDGp90DcFddWN9c/8=,tag:uD0rzUhztF6w4LW2qz48RQ==,type:str]
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Uw+Sx+gz0beXuwFM4QwXuaLsadTQBT8CbIts69S9uPESN00Aqu/pI9yk+D8=,iv:hPUgUUxYrvrbGyAO0hd/5iQpFmAJI8flZkPcTFTfai0=,tag:UD1RT1EjRVFP4WuxHP5gBw==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:NqDncRExecUvlYh3PZg4EdCowI8tZgWN+U1mKdnPrTJJ4ePQiN0dAAORexY=,iv:qd5gj01nwPdHz6NRt/mQZEItFev5AR5kyCQDPKb+kRM=,tag:fgz0xegNCTEu05QvnoV/Jw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ui0XUh9QoaQyLvKMlIG3jPH1ZIRWqsimvWAEMZO9+2Ty0CRBdu5tEQ==,iv:ZZjFCdg4GXMhppIxlEIlIiATAfJVT0rqQrKmUbED1Zk=,tag:DI43DByM61kBvMP3HIfQ7A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:xZALubxTxVWYUrquNgfchQ4X1lzLxIh8Z3MAmEipBsrvqnySPbNEhw==,iv:HnsStDMrEADVdC0ha8ZtO1cDr+X9aeNQlmYsRBtdBt0=,tag:13DONIMOeAd+7RlVn+oZHA==,type:str]
sops:
    age:
        - recipient: age1z744d4wf8529hku99tfzs9lhkzxf4avwf7nmdp2lv27hk2ufapqst4raqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N0xzUGVZOW1PQUNpakNq
            WWwrbWtGTU1WZHp6NXNJWmh3ZUUzM21KdEJjClkzMFJwRGc2NEQ1OWxNNlRoVnBC
            Ty9IYUl2aStHbzFTNjVPTW1hY2gxUE0KLS0tIGR5dklXakVPc1o4UndvcnYvNk1D
            MTBLN3VFQlNVaTlSVzBvZlpVTEplQXMKmcWn6hX2OfrC7hEZv3agh7tzSMlfrUE/
            +zKOuoO/Ncgmww7D4Vqicpfy7chYJsJQKsLpnNCDQXC6f3oQDIvlsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T09:42:42Z"
    mac: ENC[AES256_GCM,data:V+TaHN7Sp9bgyDNeeeFoytaxeRI+V2r8FmimYE/iN1X8Jc8PPco6L08kNwDrc8nl3fkv3lbfOrTE1jNmzuHiJ9lA4+ORhe0SivW2WY4qp+ONXpnPv/BobP/edG6edjDP/d5nNxFwN33TNKPldRSvtBMJKddWvAedn4zpiKXwWyk=,iv:SeRFrW4jjIinAPbncHqV3aHDjH6lpQ2kYtpIiIhzEUk=,tag:CE1sB/tWr0TbMr6MoQEAgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
