apiVersion: ENC[AES256_GCM,data:Qsg=,iv:/qG/3AivC5YuE2XLsjLSgstsh78dyuj/fmrE/KTfLG4=,tag:nIMNYrKVQGLbLEFP2Z5kZA==,type:str]
kind: ENC[AES256_GCM,data:JiPll27W,iv:q2GERVPAUeSDRNg9Cg3OZsHmjMJrGObDOBm2MWEeWGU=,tag:ITVaqB1AdqtPc6fJxSH6Sg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4iJ0MP/E/5LGeLUgKiY9IRk=,iv:c2ZYGccPwXbDKltSrqBOalOLOM3htp/y07SD70ju7rA=,tag:FnBj1z5dEMkX02vr6j7A4Q==,type:str]
    namespace: ENC[AES256_GCM,data:mhPa+7YpJLD3,iv:0fRcBLO+pSqh/UAU3UA3xcytZZQzD3ZOSNFUrn/TU38=,tag:lGCQNelJZvF9wLBru86qaQ==,type:str]
type: ENC[AES256_GCM,data:bx7Jj0yx,iv:a4RN4Z8zRIo13776V0Y26iemOon8jDuJmc8NoTBnab0=,tag:fpWkaJiPFaWudkE8WJHINQ==,type:str]
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:mu0TESvSgvr93rpYzcmYt2GonxPjeM4V8gxTX6V/WsPnpC2JSFMDZTktao0=,iv:E6bHZt6jFkDlxq9AY7pHCfkK7nInD/EWblJof4JamD8=,tag:dJXsftWIDcgBmhOA+rghXw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:uM1ab7LX0JgFZ+SNPP4ub3ZiWMWqZ4tWi7un1LaHf8y08mircXTj9RuzvnE=,iv:cukQ53uNDBHpGhk3BYQcjuiPjPCqNbFFw1YT/X6jXww=,tag:g05tQVr+ubmeSI9WzArkaw==,type:str]
    SITE_URL: ENC[AES256_GCM,data:yi10rRIN61acVhTd0KpLWCzp8o/oUW+ItHegRN9inw==,iv:Q6HP/wfCXDV84Fqhx/wFnHg9J98b69aimGqkJmIiO8U=,tag:FC2FVBAomAgodEAs4Sgy9w==,type:str]
sops:
    age:
        - recipient: age1z744d4wf8529hku99tfzs9lhkzxf4avwf7nmdp2lv27hk2ufapqst4raqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUE9QNmd1clJ3bVZlMW9y
            NmVpckZ0bGk3RDNZNzIwZ01sQXQvZVdINlZ3ClQya201MHFUM3hQRXBlM0piYUlN
            RnlXajBRRFBFcm84ZFZkWVBVcGJzdk0KLS0tIFFzNGhPS0ZJc2NzemMwajVpc3JF
            a2NDV09oYXFBd0FhKy9yOEdOOVRkUE0KR2tJdQUu2rypmRhp7J5zWkaVdXD50Xgj
            T8Mg2JV9mhV5B0zWD6Chp6iv6KVT2V/JGpRGTrvHx+hQzwDR0SkyUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T13:15:59Z"
    mac: ENC[AES256_GCM,data:snmWNCOjENgJcesdJR5pMLmSM7HUy5KAm5IIHbe9yQZuB6+1O+Yxoddsmd94FvuFo0R100u5KKJ9TyZxcUIEcJQZK+ni2uMMWjEWoYKrl2CtykNU1lFLalX9j60fcLj23oAll7L56ZwNln2yK+GrQOT18VHcUaLXp917lE7bEGc=,iv:OcY+e+fK4kR5Ecuvy/0E2w7UGwrghHp0p+NOznojULY=,tag:hSPWifEmHly239vt4IP9nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
