infisical:
  enabled: true
  image:
    repository: infisical/infisical
    tag: "v0.151.0"
    pullPolicy: IfNotPresent
  replicaCount: 1
  kubeSecretRef: "infisical-secrets"
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 350m

ingress:
  enabled: false

postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: local-path
      size: 8Gi

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      storageClass: local-path
      size: 8Gi