infisical:
  enabled: true
  image:
    repository: infisical/infisical
    tag: "v0.151.0"
    pullPolicy: IfNotPresent
  replicaCount: 1
  kubeSecretRef: "infisical-secrets"
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 350m

ingress:
  enabled: true
  hostName: "infisical.homelab.local"
  ingressClassName: traefik
  nginx:
    enabled: false
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    - secretName: infisical-tls
      hosts:
        - infisical.homelab.local

postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: local-path
      size: 8Gi

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      storageClass: local-path
      size: 8Gi