apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: github-webhook-token-secret
    creationPolicy: Owner
    template:
      data:
        username: Jaeensson
        token: "{{ .GITHUB_WEBHOOK_TOKEN }}"
  data:
    - secretKey: GITHUB_WEBHOOK_TOKEN
      remoteRef:
        key: github-webhook-token