---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-webhook-token
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 10m

  authentication:
    universalAuth:
      secretsScope:
        # either projectSlug or projectId is required
        projectSlug: homelab
        envSlug: prod
        secretsPath: "/"
         # OPTIONAL: If you want to fetch a single Infisical secret, you can specify the secret name here. If not specified, all secrets in the specified scope will be fetched.
        secretName: github-webhook-token
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system

  managedKubeSecretReferences:
    - secretName: github-webhook-token
      secretNamespace: flux-system
