---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-web-token
  namespace: cert-manager
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 10m

  authentication:
    universalAuth:
      secretsScope:
        # either projectSlug or projectId is required
        projectSlug: homelab
        envSlug: prod
        secretsPath: "/"
         # OPTIONAL: If you want to fetch a single Infisical secret, you can specify the secret name here. If not specified, all secrets in the specified scope will be fetched.
        secretName: github-web-token
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system

  managedKubeSecretReferences:
    - secretName: github-web-token
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        data: 
          token: "{{ .KEY.Value }}"
