---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-webhook-token
  namespace: flux-system
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsContext:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
  managedKubeSecretReferences:
    secretName: github-webhook-token-secret
    secretNamespace: flux-system
    template:
      data:
        username: Jaeensson
        token: "{{ .github-webhook-token }}"
  source:
    projectId: "34bcf314-3513-4e8d-9ce9-a9d3246232e9"
    envSlug: "prod"
    path: "/"
