---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool"
spec:
  blocks:
    - start: 192.168.0.1
      stop: 192.168.0.254
  allowFirstLastIPs: "No"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kube-api
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: k8s.egenintres.se
#     lbipam.cilium.io/ips: 192.168.69.120
# spec:
#   type: LoadBalancer
#   externalTrafficPolicy: Local
#   selector:
#     k8s-app: kube-apiserver
#     tier: control-plane
#   ports:
#     - port: 6443