---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-admin-password
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 10m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab
        envSlug: prod
        secretsPath: "/grafana"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
  managedKubeSecretReferences:
    - secretName: grafana-admin-password-secret
      secretNamespace: observability
