---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: network
spec:
  chartRef:
    kind: OCIRepository
    name: metallb
  interval: 1h
  values:
    controller:
      enabled: true
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    speaker:
      enabled: true
      securityContext:
        allowPrivilegeEscalation: true
        runAsNonRoot: false
        runAsUser: 0
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
