apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60 # Check for updates every 60 seconds
  authentication:
    universalAuth:
      secretsContext:
        secretName: infisical-universal-auth
        secretNamespace: external-secrets
  
  managedKubeSecretReferences:
    secretName: cloudflare-api-token-secret
    secretNamespace: cert-manager
    template:
      data:
        CLOUDFLARE_DNS_TOKEN: "{{ .cloudflare-api-token }}"

  source:
    projectId: "34bcf314-3513-4e8d-9ce9-a9d3246232e9"
    envSlug: "prod"
    path: "/cloudflare"