---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
spec:
  hostAPI: https://eu.infisical.com/api
  syncConfig:
    resyncInterval: 10m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab
        envSlug: prod
        secretsPath: "/cloudflare"
        # Remove for all secrets
        secretName: CLOUDFLARE_API_TOKEN
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
  managedKubeSecretReferences:
    - secretName: cloudflare-api-token
      secretNamespace: cert-manager
      template:
        data:
          token: "{{ .CLOUDFLARE_API_TOKEN.Value }}"
