apiVersion: secrets.infisical.com/v1
kind: InfisicalSecret
metadata:
  name: example-secrets
  namespace: default
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuthCredentials:
      clientId:
        secretName: infisical-credentials
        secretKey: clientId
      clientSecret:
        secretName: infisical-credentials
        secretKey: clientSecret
  secretsConfig:
    secrets:
      - secretName: EXAMPLE_SECRET
        secretPath: /example-path
        sourceSecretKey: EXAMPLE_KEY
  managedSecret:
    secretName: example-managed-secret
    secretNamespace: default