apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  chartRef:
    kind: OCIRepository
    name: traefik
  interval: 1h
  values:
    gateway:
      enabled: false
    gatewayClass:
      enabled: false
    api:  
      dashboard: true
      insecure: false
      disabledashboardad: true

    providers:
      # @schema additionalProperties: false
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        # -- Toggles support for the Experimental Channel resources (Gateway API release channels documentation).
        # This option currently enables support for TCPRoute and TLSRoute.
        experimentalChannel: false
        # -- Array of namespaces to watch. If left empty, Traefik watches all namespaces. . When using `rbac.namespaced`, it will watch helm release namespace and namespaces listed in this array.
        namespaces: []
        # -- A label selector can be defined to filter on specific GatewayClass objects only.
        labelSelector: ""
        # -- Defines whether to use Native Kubernetes load-balancing mode by default.
        nativeLBByDefault: false
        statusAddress:
          hostname: "traefik.test.egenintres.se"
          

      # @schema additionalProperties: false
      file:
        # -- Create a file provider
        enabled: false
        # -- Allows Traefik to automatically watch for file changes
        watch: true
        # -- File content (YAML format, go template supported) (see https://doc.traefik.io/traefik/providers/file/)
        content: ""

    ports:
      web:
        address: :80
        port: 8000
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: :443
        port: 8443
        http:
          # -- See [upstream documentation](https://doc.traefik.io/traefik/security/request-path/#encoded-character-filtering)
          # encodedCharacters:  # @schema additionalProperties: false
          #   allowEncodedSlash:  # @schema type:[boolean, null]
          #   allowEncodedBackSlash:  # @schema type:[boolean, null]
          #   allowEncodedNullCharacter:  # @schema type:[boolean, null]
          #   allowEncodedSemicolon:  # @schema type:[boolean, null]
          #   allowEncodedPercent:  # @schema type:[boolean, null]
          #   allowEncodedQuestionMark:  # @schema type:[boolean, null]
          #   allowEncodedHash:  # @schema type:[boolean, null]
          # -- Maximum size of request headers in bytes. Default: 1048576 (1 MB)
          maxHeaderBytes: 1048576
          # -- See [upstream documentation](https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/#httpmiddlewares)
          #middlewares: []  # @schema type: [array, null]
          # sanitizePath:  # @schema type:[boolean, null]
          tls:
            enabled: true
        http3:
          ## -- Enable HTTP/3 on the entrypoint
          ## Enabling it will also enable http3 experimental feature
          ## https://doc.traefik.io/traefik/routing/entrypoints/#http3
          ## There are known limitations when trying to listen on same ports for
          ## TCP & UDP (Http3). There is a workaround in this chart using dual Service.
          ## https://github.com/kubernetes/kubernetes/issues/47249#issuecomment-587960741
          enabled: false
          advertisedPort:  # @schema type:[integer, null]; minimum:0
        forwardedHeaders:
            # -- Trust forwarded headers information (X-Forwarded-*).
          trustedIPs: []
          insecure: false
        
    persistence:
      # -- Enable persistence using Persistent Volume Claims
      # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
      # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
      enabled: false
      name: data
      existingClaim: ""
      accessMode: ReadWriteOnce
      size: 128Mi
      storageClass:  # @schema type:[string, null]
      volumeName: ""
      path: /data
      annotations: {}
      # -- Only mount a subpath of the Volume into the pod
      subPath: ""
    hostNetwork: false