repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: bedag
    url: https://bedag.github.io/helm-charts
  - name: wiremind
    url: https://wiremind.github.io/wiremind-helm-charts

releases:
  # --- STAGE: CRDS ---
  - name: gateway-api-crds
    namespace: kube-system
    chart: wiremind/gateway-api-crds
    version: 1.4.0
    labels:
      stage: crds

  # --- STAGE: INFRA ---
  - name: traefik
    chart: traefik/traefik
    namespace: traefik
    version: 39.0.1
    createNamespace: true
    needs:
      - kube-system/gateway-api-crds
    labels:
      stage: infra
    values:
      - traefik/values.yaml

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.15.3
    createNamespace: true
    labels:
      stage: infra
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["label", "--overwrite", "namespace", "metallb-system", "pod-security.kubernetes.io/enforce=privileged"]

  # --- STAGE: CONFIG ---
  - name: metallb-config
    namespace: metallb-system
    chart: bedag/raw
    labels:
      stage: config
    needs:
      - metallb-system/metallb
    values:
      - metallb/metallb-conf.yaml