bases:
  - _repositories.yaml

releases:
  - name: gateway-api-crds
    namespace: kube-system
    chart: wiremind/gateway-api-crds
    version: 1.4.0

  - name: traefik
    chart: traefik/traefik
    namespace: traefik
    version: 39.0.1
    createNamespace: true
    needs:
      - kube-system/gateway-api-crds
    values:
      - ../traefik/values.yaml

  - name: traefik-dashboard-route
    namespace: traefik
    chart: bedag/raw
    needs:
      - traefik/traefik
    values:
      - resources:
          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: traefik-dashboard
            spec:
              parentRefs:
                - name: traefik-gateway
                  namespace: traefik
                  sectionName: websecure
              hostnames:
                - dashboard.homelab.local
              rules:
                - backendRefs:
                    - name: api@internal
                      group: traefik.io
                      kind: TraefikService