apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-universal-auth
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-universal-auth
            namespace: external-secrets
      secretsScope:
        projectSlug: homelab
        environmentSlug: prod
